name: test-login-flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  login-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install runhouse
          pip install pytest 

      - name: run login flow tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: pytest tests/test_login.py