name: Run tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Runhouse
        run: python -m pip install --upgrade pip && pip install -e .

      - name: Install testing dependencies
        run: pip install pytest s3fs==2023.1.0 awscli==1.25.60 boto3==1.24.59 pycryptodome==3.12.0 \
             google-api-python-client google-cloud-storage gcsfs datasets dask

      - name: run tests
        run: pytest tests/
